namespace Servidor.Models
{
    public enum Tipo
    {
        SUMA,
        RESTA,
        MULTIPLICACION,
        DIVISION,
        NEGATIVO,
        ENTERO,
        DECIMAL,
        BOOLEANO,
        TIME,
        DATE,
        MAP,
        SET,
        LIST,
        IDENTIFICADOR,
        CADENA,
        MAYOR_QUE,
        MENOR_QUE,
        CONCATENACION,
        FUNCION,
        METODO,
        ARREGLO,
        OBJETO,
        VARIABLE,
        NO_ACEPTADO
    }
}